### ISSUE TITLE
Bug /SRTP

### ISSUE THREAD

**Issue by Alexandre2500** [stan1712/SeriousRP#18]
Je ne peux pas faire de /srtp dans le monde minérale

**Comment by stanislasbdx** [comment]
Bonjour, c'est à dire ? Que s'est t'il passé ?

**Comment by Alexandre2500** [comment]
Quans je fais un srtp ça me met un message d'erreur dans le chat mais je ne serais pas dit lequel

**Comment by Alexandre2500** [comment]
Je vais allez regarder

**Comment by Alexandre2500** [comment]
Oups

**Comment by Alexandre2500** [comment]
Message d'erreur : I'm sorry, but you do not have permission to perform this command. Please contact de server administrators if you believe that this is in error.

**Comment by stanislasbdx** [comment]
Merci, je règle ça le plus rapidement possible

`
- srv : wetstonrp
- map : mineral
- grd joueur : citoyen
`
