### ISSUE TITLE
Open sourced without license

### ISSUE THREAD

**Issue by MrIvanPlays** [stan1712/SeriousRP#30]
This means no one except you can make PRs, or use parts of the code. Either you need to add a license, or just don't make the plugin open sourced. Your TOS in spigot doesn't legally apply here, I can steal this, rename packages & stuff and distribute the plugin as my own. I don't want to do that, that's why I'm opening this issue you should look at.

**Comment by stanislasbdx** [comment]
Hello!
I don't find a license wich allows people to improve the plugin by modifying it and then make a pull request :x
I searched on https://choosealicense.com but I'm pretty new to licensing, do you have an exemple of license I can use ?

**Comment by MrIvanPlays** [comment]
You can start with the [MIT License](https://choosealicense.com/licenses/mit/). Just add a LICENSE file in your github repo and add the contents of the license.
