### ISSUE TITLE
Cheque bug

### ISSUE THREAD

**Issue by noahplanche** [stan1712/SeriousRP#34]
1) Quand on a plus de place dans son inventaire et que l'ont crée un cheque il dissparait dans les abîmes.

2) Quand on a plusieurs cheque du même montant dans son inventaire et que l'ont en encaisse 1 tous sont détruit.

**Comment by stanislasbdx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Cheque bug](https://trello.com/c/JB2v7wTa/3-cheque-bug)

**Comment by stanislasbdx** [comment]
> Quand on a plusieurs cheque du même montant dans son inventaire et que l'ont en encaisse 1 tous sont détruit.

Effectivement, et cela ne sera pas corrigé je pense. A moins que ce soit un réel problème.

**Comment by stanislasbdx** [comment]
> Quand on a plus de place dans son inventaire et que l'ont crée un cheque il dissparait dans les abîmes.

C'est corrigé, ce sera dispo sur la 4.0.5f
