### ISSUE TITLE
Permanent death

### ISSUE THREAD

**Issue by stanislasbdx** [stan1712/SeriousRP#35]
If we die near a block or a carpet, we kept dying in a loop and then, we get kicked by the server...

**Comment by stan1712** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [test](https://trello.com/c/BlDCBdZv/1-test)

**Comment by stanislasbdx** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Permanent death](https://trello.com/c/ZbDy2HXx/4-permanent-death)
